version: "3.9"

services:
  web:
    build: ./
    container_name: face_search_web
    command: bash entrypoint.sh
    volumes:
      - .:/face_search
      - ./static:/face_search/static
      - ./media:/face_search/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    container_name: face_search_db
    volumes:
      - .:/face_search
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: face_search_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web