# Generated by Django 4.0 on 2023-03-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('vk', 'ВКонтакте'), ('ok', 'Одноклассники'), ('tg', 'Телеграм'), ('fb', 'Фейсбук'), ('viber', 'Вайбер')], max_length=100)),
                ('profile_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('passport', 'Паспорт'), ('driver_license', 'Водительские удостоверение')], max_length=100)),
                ('document_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField()),
            ],
            options={
                'verbose_name': 'Обличче',
                'verbose_name_plural': 'Обличчя',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('face_documentmodel', 'Документы'), ('face_avatarmodel', 'Аватары')], max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='face.facemodel')),
            ],
            options={
                'verbose_name': "Зв'язок",
                'verbose_name_plural': "Зв'язки",
                'ordering': ['id'],
            },
        ),
    ]
